services:
  backend:
    container_name: backend
    build: ./src/
    ports:
      - 3000:3000
    volumes:
      - ./src/frontend:/frontend:rw
      - ./src/backend/db:/backend/db:rw
    env_file:
      - .env


    